server:
  port: 8888
spring:
  application:
    name: smart-invoice-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:./../config-repo
